In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("clean_cafe_sales.csv")
df.drop(columns=["Unnamed: 0"],inplace=True)
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08 00:00:00
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-Store,2023-05-16 00:00:00
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-Store,2023-07-19 00:00:00
3,TXN_7034554,Salad,2,5.0,10.0,Cash,In-Store,2023-04-27 00:00:00
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-Store,2023-06-11 00:00:00
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,Cash,In-Store,2023-08-30 00:00:00
9996,TXN_9659401,Coffee,3,2.0,6.0,Digital Wallet,In-Store,2023-06-02 00:00:00
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,In-Store,2023-03-02 00:00:00
9998,TXN_7695629,Cookie,3,3.0,9.0,Digital Wallet,In-Store,2023-12-02 00:00:00
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-Store,2023-11-07 00:00:00

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              10000 non-null  str
 2   Quantity          10000 non-null  int64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       10000 non-null  float64
 5   Payment Method    10000 non-null  str
 6   Location          10000 non-null  str
 7   Transaction Date  10000 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 625.1 KB

In [6]:
df.describe()

          Quantity  Price Per Unit   Total Spent
count  10000.00000    10000.000000  10000.000000
mean       3.01800        2.952400      8.914692
std        1.40459        1.260603      5.900160
min        1.00000        1.000000      1.000000
25%        2.00000        2.000000      4.000000
50%        3.00000        3.000000      8.000000
75%        4.00000        4.000000     12.000000
max        5.00000        5.000000     25.000000